# Generated by Django 5.1.3 on 2024-12-28 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('join_code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('format', models.PositiveSmallIntegerField(choices=[(2, '2v2'), (3, '3v3'), (4, '4v4'), (5, '5v5')])),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PickupPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='users.pickupgame')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.membership')),
            ],
        ),
        migrations.AddField(
            model_name='pickupgame',
            name='all_invited_players',
            field=models.ManyToManyField(blank=True, related_name='invited_games', to='users.pickupplayer'),
        ),
        migrations.AddField(
            model_name='pickupgame',
            name='assigned_players',
            field=models.ManyToManyField(blank=True, related_name='assigned', to='users.pickupplayer'),
        ),
        migrations.AddField(
            model_name='pickupgame',
            name='pending_players',
            field=models.ManyToManyField(blank=True, related_name='pending_games', to='users.pickupplayer'),
        ),
        migrations.AddField(
            model_name='pickupgame',
            name='unassigned_players',
            field=models.ManyToManyField(blank=True, related_name='unassigned_games', to='users.pickupplayer'),
        ),
        migrations.CreateModel(
            name='PickupTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ringers', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='users.pickupgame')),
            ],
        ),
        migrations.AddField(
            model_name='pickupplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='users.pickupteam'),
        ),
    ]
