# Generated by Django 5.1.3 on 2024-12-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pickupgame_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='friends',
            field=models.ManyToManyField(blank=True, to='users.membership'),
        ),
    ]
