# Generated by Django 5.1.3 on 2024-12-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_membership_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='friend_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
