# Generated by Django 5.1.3 on 2024-12-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_membership_friend_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='friend_invites',
            field=models.ManyToManyField(blank=True, to='users.membership'),
        ),
        migrations.AddField(
            model_name='membership',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, to='users.membership'),
        ),
    ]
