# Generated by Django 5.1.3 on 2024-12-28 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_membership_friend_invites_membership_friend_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='friend_invites',
            new_name='received_requests',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='friend_requests',
            new_name='sent_requests',
        ),
    ]
