# Generated by Django 5.1.3 on 2024-12-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_friend_invites_membership_received_requests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='received_requests',
        ),
        migrations.AlterField(
            model_name='membership',
            name='sent_requests',
            field=models.ManyToManyField(blank=True, related_name='received_requests', to='users.membership'),
        ),
    ]
