# Generated by Django 5.1.3 on 2024-12-29 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_membership_received_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='pickup_losses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='pickup_wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pickupplayer',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='users.pickupteam'),
        ),
    ]
