# Generated by Django 5.1.3 on 2024-12-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_membership_pickup_losses_membership_pickup_wins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupgame',
            name='all_members',
            field=models.ManyToManyField(blank=True, related_name='pickup_games', to='users.membership'),
        ),
    ]
