# Generated by Django 5.1.3 on 2024-12-30 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_pickupgame_ballers_score_pickupgame_ringers_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupgame',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_games', to='users.membership'),
        ),
    ]
