# Generated by Django 5.1.3 on 2025-01-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_pickupgame_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupteam',
            name='name',
            field=models.CharField(default='get_default_name', max_length=50),
        ),
    ]
