# Generated by Django 5.1.3 on 2025-01-01 07:08

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_pickupteam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupteam',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
