# Generated by Django 5.1.3 on 2025-01-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_pickupteam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupteam',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
