# Generated by Django 5.1.3 on 2025-01-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_membership_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupgame',
            name='join_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
