# Generated by Django 5.1.3 on 2025-01-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_pickupgame_join_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickupgame',
            old_name='all_invited_players',
            new_name='all_players',
        ),
        migrations.AddField(
            model_name='pickupgame',
            name='requesting_players',
            field=models.ManyToManyField(blank=True, related_name='requested_games', to='users.pickupplayer'),
        ),
    ]
