# Generated by Django 5.1.3 on 2025-01-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_all_invited_players_pickupgame_all_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='losses_3v3',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='losses_4v4',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='losses_5v5',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='wins_3v3',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='wins_4v4',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='wins_5v5',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
