# Generated by Django 5.1.3 on 2025-01-11 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_membership_losses_3v3_membership_losses_4v4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationGameGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_groups', to='users.pickupgame')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_groups', to='users.membership')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.notificationgamegroup')),
            ],
        ),
    ]
