# Generated by Django 5.1.3 on 2025-01-11 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_notificationgamegroup_notificationgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationgame',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_notifications', to='users.membership'),
            preserve_default=False,
        ),
    ]
