# Generated by Django 5.1.3 on 2025-01-11 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_notificationgame_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationgamegroup',
            name='game',
        ),
        migrations.RemoveField(
            model_name='notificationgamegroup',
            name='member',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_notifications', to='users.membership')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_notifications', to='users.pickupgame')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.membership')),
            ],
        ),
        migrations.DeleteModel(
            name='NotificationGame',
        ),
        migrations.DeleteModel(
            name='NotificationGameGroup',
        ),
    ]
